version: "3.8"

services:
  redis:
    container_name: cache
    image: redis:alpine3.22
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - "D:/.database/redis:/data"
    networks:
      - app-network

  database:
    image: postgres:16
    container_name: database
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-database}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-cadsquaddb}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - "D:/.database/postgres:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-cadsquaddb}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:3
    container_name: ngrok
    restart: unless-stopped
    ports:
      - "4040:4040"
    depends_on:
      - backend
      # - web_client
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml:ro
    env_file:
      ./.env
    command: ["start", "--all", "--config", "/etc/ngrok.yml"]
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    networks:
      - app-network

  prisma-studio:
    build:
      context: ./server
      target: runner
    container_name: prisma-studio
    command: npx prisma studio --schema=./prisma/schema.prisma
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-database}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-cadsquaddb}?schema=public
    ports:
      - "5555:5555"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network

  backend:
    build: ./server
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      NODE_ENV: ${NODE_ENV}
      BACKEND_PORT: ${BACKEND_PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-database}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-cadsquaddb}?schema=public
      CLIENT_URL: ${CLIENT_URL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAILER_SECURE: ${MAILER_SECURE}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_FROM: ${MAIL_FROM}
      SMTP_URL: ${SMTP_URL:-smtp://${MAIL_USER}:${MAIL_PASS}@${MAIL_HOST}}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRES_AT: ${JWT_EXPIRES_AT}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_FOLDER_ROOT: ${CLOUDINARY_FOLDER_ROOT}
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - app-network

  # web_client:
  #   build: ./client
  #   container_name: web_client
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - database
  #     - backend
  #   environment:
  #     NODE_ENV: ${NODE_ENV}
  #     NEXT_PUBLIC_APP_VERSION: ${CLIENT_VERSION:-0.0.0-release}
  #     NEXT_PUBLIC_APP_TITLE: ${CLIENT_APP_TITLE}
  #     NEXT_PUBLIC_API_ENDPOINT: ${API_URL}
  #     NEXT_PUBLIC_URL: ${CLIENT_URL}
  #     NEXT_PUBLIC_WS_URL: ${WS_URL}
  #     NEXT_PUBLIC_VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
  #     VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge