version: "3.8"

services:
  redis:
    container_name: cache
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - "D:/.database/redis:/data"

  database:
    image: postgres:16
    container_name: database
    restart: always
    env_file:
      ./server/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-cadsquaddb}
    ports:
      - "5432:5432"
    volumes:
      - "D:/.database/postgres:/var/lib/postgresql/data"

  web-frontend:
    build: ./client
    container_name: cadsquad-staff-web
    ports:
      - "3000:3000"
    depends_on:
      - database
      - backend
    env_file:
      ./client/.env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      NEXT_PUBLIC_APP_VERSION: ${NEXT_PUBLIC_APP_VERSION:-0.0.0-release}
      NEXT_PUBLIC_APP_TITLE: ${NEXT_PUBLIC_APP_TITLE:-Cadsquad Staff}
      NEXT_PUBLIC_API_ENDPOINT: ${NEXT_PUBLIC_API_ENDPOINT}
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
      NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
      NEXT_PUBLIC_VAPID_PUBLIC_KEY: ${NEXT_PUBLIC_VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}

  backend:
    build: ./server
    container_name: cadsquad-staff-backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    env_file:
      ./server/.env
    environment:
      BACKEND_PORT: ${BACKEND_PORT:-8080}
      DATABASE_URL: ${DATABASE_URL:-postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${DB_HOST:-database}:${POSTGRES_HOST:-5432}/${POSTGRES_DB:-cadsquaddb}?schema=public}
      CLIENT_URL: ${CLIENT_URL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAILER_SECURE: ${MAILER_SECURE}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_FROM: ${MAIL_FROM}
      SMTP_URL: ${SMTP_URL:-smtp://${MAIL_USER}:${MAIL_PASS}@${MAIL_HOST}}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRES_AT: ${JWT_EXPIRES_AT}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID:-test}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID:-test}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET:-test}
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_FOLDER_ROOT: ${CLOUDINARY_FOLDER_ROOT:-Cadsquad}