name: cadsquad
version: '1.0.0'

services:
  postgres:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=cadsquad
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - D:/.database:/var/lib/postgresql/data

  redis:
    container_name: cache
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - D:/.database:/data

volumes:
  postgres:
    driver: local
  cache:
    driver: local
