name = "cadsquad-staff-be"
main = "./dist/src/main.js"
compatibility_date = "2025-10-11"

compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
external = [
    "@nestjs/microservices",
    "class-transformer/storage",
    "dtrace-provider",
    "@nestjs/websockets",
    "socket.io",
]